### ISSUE TITLE
Game crash when attempting to enchant

### ISSUE THREAD

**Issue by IamStig** [Redstoneguy129/MoreBoots#2]
I am not sure if the boots are supposed to be able to be enchanted thou I don't expect the game should crash if I attempt to do so, but it does.

More Boots version ...........1.1.5*
Forge version ...................... 28.0.82*
The boot ................................Ultimate
The enchant ..........................Mending
The method ..........................Boot and book in anvil
Expected..................................Either the boots are not able to be put into anvil 
....Or...........................................I get Ultimate Boots with mending
Actual Result .........................Immediate crash when putting the Mending book in the anvil (Boots 
                                           go in first) and both the boots and the book are deleted
*also happened on 1.1.4 and earlier forge version, updated a while back but only just got around to getting another mending book and testing

**Comment by Redstoneguy129** [comment]
Fixed enchanting, thanks for the report!
